### ISSUE TITLE
A strange error is occurring. 

### ISSUE THREAD

**Issue by Starship4605** [dromzeh/hyv-fps-unlocker#6]
![image](https://github.com/dromzeh/hyv-fps-unlocker/assets/62975008/46531cf1-79a6-46ba-aa8c-2b8e514eccc4)

Game is installed and everything, even ran as admin, same issue.

**Comment by dromzeh** [comment]
I'm aware, opened an issue for it [#2] - will get a fix out shortly ^^

**Comment by dromzeh** [comment]
This is fixed. Please try [re-downloading from the releases page](https://github.com/dromzeh/hyv-fps-unlocker/releases/) and running it again :)
